[shell.animation]
speed = 2

[shell.screenshot]
save_to_file = false
directory = "~/Pictures/Screenshots"
copy_to_clipboard = true
freeze_screen = true
show_cursor = true
pipe_to_command = true
pipe_command = "satty -f - -o '~/Pictures/Screenshots/screenshot_%Y%m%d_%H%M%S.png'"

[shell.panel]
transparency_mode = "glass"
control_center_placement = "floating"
open_near_click_control_center = true
wallpaper_placement = "floating"


[osd]
position = "bottom_center" 

[location]
auto_locate = true

[lockscreen]
enabled = true
lock_before_suspend = true

[lockscreen_widgets]
enabled = true

[lockscreen_widgets.widget.clock_main]
type     = "clock"
output = "eDP-1"
cx         = 1600.0
cy         = 120.0
box_width  = 360.0
box_height = 120.0
rotation   = 0.0

[lockscreen_widgets.widget.clock_main.settings]
format = "{:%H:%M}"

[control_center]
sidebar = "full"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "audio"

[[control_center.shortcuts]]
type = "system"

[[control_center.shortcuts]]
type = "clipboard"

[system.monitor]
enabled = true

[idle]
behavior_order = ["lock", "screen-off", "suspend"]
pre_action_fade_seconds = 2.0

[idle.behavior.lock] 
timeout = 300
action = "lock" 
enabled = true

[idle.behavior.screen-off]
timeout = 360
action = "screen_off" 
enabled = true

[idle.behavior.suspend]
timeout = 1200
action = "lock_and_suspend"
