-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Keybinds
hl.bind("SHIFT + CTRL + Q", hl.dsp.exit())
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
hl.bind("SUPER + M", hl.dsp.window.fullscreen())
hl.bind("SUPER + C", hl.dsp.window.center())
hl.bind("SUPER + CTRL + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + CTRL + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("wezterm"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("microsoft-edge-stable"))
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("hyprlauncher"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + CTRL + Left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
hl.bind("SUPER + CTRL + Right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
hl.bind("SUPER + CTRL + Down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -zm region"))
hl.bind("SHIFT + CTRL + Print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("SUPER + CTRL + Up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }))
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.swap({ direction = "left" }))
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.swap({ direction = "right" }))
hl.bind("SUPER + SHIFT + Up", hl.dsp.window.swap({ direction = "up" }))
hl.bind("SUPER + SHIFT + Down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + CTRL + 1", hl.dsp.window.move({ workspace = 1, silent = true }))
hl.bind("SUPER + CTRL + 2", hl.dsp.window.move({ workspace = 2, silent = true }))
hl.bind("SUPER + CTRL + 3", hl.dsp.window.move({ workspace = 3, silent = true }))
hl.bind("SUPER + CTRL + 4", hl.dsp.window.move({ workspace = 4, silent = true }))
hl.bind("SUPER + CTRL + 5", hl.dsp.window.move({ workspace = 5, silent = true }))
hl.bind("SUPER + CTRL + 6", hl.dsp.window.move({ workspace = 6, silent = true }))
hl.bind("SUPER + CTRL + 7", hl.dsp.window.move({ workspace = 7, silent = true }))
hl.bind("SUPER + CTRL + 8", hl.dsp.window.move({ workspace = 8, silent = true }))
hl.bind("SUPER + CTRL + 9", hl.dsp.window.move({ workspace = 9, silent = true }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})
hl.bind("SUPER + mouse:273", hl.dsp.window.drag(), {
    mouse = true,
})
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + SHIFT + Tab", hl.dsp.focus({ workspace = -1 }))
