font=monospace:size=14:weight=bold
pad=10x0
shell=fish

# Windows Decorations
[colors-dark]
alpha=0.85
foreground=ffffff
background=000000
cursor=ffffff 52ad70
selection-foreground=000000
selection-background=ffffff

# Cursor
cursor=ffffff 52ad70

# Selection
selection-foreground=000000
selection-background=ffffff

# regular colors
regular0=1e1e1e    # black
regular1=ff0000    # red
regular2=00ff00    # green
regular3=ffff00    # yellow
regular4=4041FF    # blue
regular5=ff00ff    # magenta/purple
regular6=00ffff    # cyan
regular7=ffffff    # white

# bright colors
bright0=555555     # bright black
bright1=ff0000     # bright red
bright2=00ff00     # bright green
bright3=ffff00     # bright yellow
bright4=2A71FF     # bright blue
bright5=ff00ff     # bright magenta/purple
bright6=00ffff     # bright cyan
bright7=ffffff     # bright white

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes